### PR TITLE
Wahlbezirke blog

### PR DESCRIPTION
**Pull request by tori-d**
Initiating pull request to generate Netlify preview; PR should not yet be merged.

### CODE REVIEW

**Comment by tori-d** [comment]
Branch is now ready for merging; requesting review from @dnsos

**Review by dnsos — CHANGES_REQUESTED** [review]
Hey @tori-d and @evelynebrie, looks great! One thing I would ask: Can you compress the images you used? Some of them are quite big and they slow down loading. You can use a command line tool for that or online services like [TinyPNG](https://tinypng.com/)

**Comment by tori-d** [comment]
> Hey @tori-d and @evelynebrie, looks great! One thing I would ask: Can you compress the images you used? Some of them are quite big and they slow down loading. You can use a command line tool for that or online services like [TinyPNG](https://tinypng.com/)

Ok, I replaced the images with lower-res versions. Can you take another look, @dnsos?

**Review by dnsos — APPROVED** [review]

**Comment by dnsos** [comment]
Thanks @tori-d.  I also optimised the images a bit more. Would go ahead and merge this now!

**Pull request merged**
