### PR TITLE
update team --> text / pics / alumni

### PR DESCRIPTION
**Pull request by julizet**
### What`s new:

**moved to Alumni**
* Seb
* Fab D.

**added to team** (each: photo + dec + text (+github and/or twitter-handle))
* Ingo
* Niklas
* Christian
* Rikko 
* Jerry
* Yannick 
* Dennis

**updated**
* Sina – image
* Julia - desc + text
* Gosia – English translation

**fixed**
* small typos

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
Should we also list as suporters auth0 and 1password?

**Review by fabianmoronzirfas — DISMISSED** [review]
LGTM! 🚀

**Comment by fabianmoronzirfas** [comment]
@jvolker can you contribute a text about you in DE and EN

**Review by dnsos — DISMISSED** [review]
A typo in Christian's description: "Werkstunden" -> "Werkstudent".

**Comment by Esshahn** [comment]
crunched down some of the images with tinypng.

**Comment by julizet** [comment]
status quo:
* alle image placeholders are replaced with personal images
* only text of @jvolker and @Sarapedia  are missing -> Please add you text

**Review by fabianmoronzirfas — DISMISSED** [review]
LGTM I did not review texts

**Review by fabianmoronzirfas — APPROVED** [review]
LGTM

**Comment by Esshahn** [comment]
checked on mobile, looking good

**Review by dnsos — APPROVED** [review]

**Pull request merged**
