### PR TITLE
fix(RSS Feed Title and description)

### PR DESCRIPTION
**Pull request by fabianmoronzirfas**
This PR adds:

- RSS Feed for DE and EN
- `<!--more-->` tag for creating excerpts
- docs how to use excerpt
- updates node-sass due to build error

Added description and title from `data.meta.…`

re #198

### CODE REVIEW

**Comment by bnjmnsbl** [comment]
small, non-breaking bugs:
- not all posts show excerpts (especially in german feed)
- excerpts show markdown formatting (i.e. "The average Berliner spends an **average of 154 hours a year sitting in traffic jams** ([INRIX Traffic Study (German)](http://inrix.com/scorecard/)"),

I'm on the "better done than perfect" team with this one, so if it's too much of a hassle to fix I guess we can live with it

**Comment by fabianmoronzirfas** [comment]
> - not all posts show excerpts (especially in german feed)

The excerpt is opt-in you will have to define an excerpt in the file by using the html comment. Since we don't have these yet it strips the html and truncateds at 50 words

```html
<!--more-->
```

**Comment by fabianmoronzirfas** [comment]
> - excerpts show markdown formatting 

is fixed

**Comment by bnjmnsbl** [comment]
> > * not all posts show excerpts (especially in german feed)
> 
> The excerpt is opt-in you will have to define an excerpt in the file by using the html comment. Since we don't have these yet it strips the html and truncateds at 50 words
> 
> ```
> 
> ```

nevermind, this was an issue with my feedreader...i'd say we are ready to merge then?

**Comment by fabianmoronzirfas** [comment]
@bnjmnsbl Yes. Ready to merge! 🚀

**Pull request merged**
